/*
    Tesla BLE Scanner for Bruce
    Based on Esp32vsEvil's TeslaScanner: https://github.com/Esp32vsEvil/TeslaScanner
    Modified by dudgy

    Note: This is experimental software for educational purposes.
    Detection may not work reliably and results are not guaranteed.
*/

#include "ble_tesla.h"
#include "core/mykeyboard.h"
#include "core/utils.h"
#include "core/sd_functions.h"
#include <map>
#include <vector>

#define SCAN_INTERVAL 100
#define SCAN_WINDOW 99

static NimBLEScan* pBLEScan;
static bool teslaScanning = false;
static bool scanCancelled = false;

std::map<String, TeslaInfo> teslaHistory;
bool exportRequested = false;

class TeslaAdvertisedDeviceCallbacks : public NimBLEAdvertisedDeviceCallbacks {
    void onResult(NimBLEAdvertisedDevice* advertisedDevice) {
        if (scanCancelled) return;

        if (advertisedDevice->haveName()) {
            String deviceName = String(advertisedDevice->getName().c_str());

            /*
            Detect Tesla devices by name pattern assumes:
            - Model S: Names starting with 'S' and 18 characters long ending with 'C'
            - Other Models: Names starting with 'Tesla'
            */
            if ((deviceName.length() >= 18 && deviceName.charAt(0) == 'S' && deviceName.charAt(17) == 'C') ||
                deviceName.startsWith("Tesla")) {

                String address = advertisedDevice->getAddress().toString().c_str();
                int rssi = advertisedDevice->getRSSI();

                // Update or add to Tesla history
                teslaHistory[address] = { address, rssi, millis(), deviceName };
            }
        }
    }
};

void BLETesla::drawMainBorder() {
    ::drawMainBorder(); // Use global function
    tft.drawString("-=Tesla Scanner=-", (tftWidth / 2) - ((16 * 6) / 2), 12);
}

String formatTime(unsigned long timestamp) {
    unsigned long secondsAgo = (millis() - timestamp) / 1000;

    if (secondsAgo < 60) {
        return String(secondsAgo) + "s";
    }
    else if (secondsAgo < 3600) {
        return String(secondsAgo / 60) + "m";
    }
    else {
        return String(secondsAgo / 3600) + "h";
    }
}

void updateTeslaDisplay() {
    static unsigned long lastUpdate = 0;

    if (millis() - lastUpdate < 500) {
        return;
    }

    lastUpdate = millis();

    // Clear the content area
    tft.fillRect(10, 35, tftWidth - 20, tftHeight - 50, bruceConfig.bgColor);

    // Display Tesla history with timestamps
    int yPos = 35;
    for (const auto& tesla : teslaHistory) {
        String timeStr = formatTime(tesla.second.lastSeen);
        String displayText = tesla.second.name + " " + String(tesla.second.rssi) + "dBm (" + timeStr + ")";

        // Visual signal strength indicator
        int signalBars = map(constrain(tesla.second.rssi, -100, -50), -100, -50, 1, 5);
        String strength = " [";
        for (int i = 0; i < signalBars; i++) strength += "|";
        for (int i = signalBars; i < 5; i++) strength += " ";
        strength += "]";

        tft.setTextColor(bruceConfig.priColor, bruceConfig.bgColor);
        tft.drawString(displayText + strength, 10, yPos);
        yPos += 12;

        if (yPos > tftHeight - 20) break;
    }

    if (teslaHistory.empty()) {
        tft.setTextColor(bruceConfig.priColor, bruceConfig.bgColor);
        tft.drawString("No Teslas detected yet", 10, 35);
    }

    // Show controls
    tft.setTextColor(bruceConfig.secColor, bruceConfig.bgColor);
    tft.drawString("C=Clear  E=Export  Esc=Exit", 10, tftHeight - 20);
}

bool exportTeslaHistory() {
    if (!setupSdCard()) {
        displayTextLine("SD Card not found!");
        delay(1000);
        return false;
    }

    String filename = "/tesla_scan.txt";

    int counter = 1;
    while (SD.exists(filename)) {
        filename = "/tesla_scan_" + String(counter) + ".txt";
        counter++;
    }

    File file = SD.open(filename, FILE_WRITE);
    if (!file) {
        displayTextLine("Failed to create file!");
        delay(1000);
        return false;
    }

    file.println("Tesla BLE Scan Results");
    file.println("Generated by Bruce Tesla Scanner");
    file.println("Scan duration: " + String(millis() / 1000) + " seconds");
    file.println("Total devices: " + String(teslaHistory.size()));
    file.println("=================================");
    file.println();

    for (const auto& tesla : teslaHistory) {
        String timeStr = formatTime(tesla.second.lastSeen);
        String line = "MAC: " + tesla.second.address +
            " | Name: " + tesla.second.name +
            " | RSSI: " + String(tesla.second.rssi) + "dBm" +
            " | Last Seen: " + timeStr + " ago";
        file.println(line);
    }

    file.close();

    // Verify file was written
    if (SD.exists(filename)) {
        displayTextLine("Exported: " + String(teslaHistory.size()) + " devices");
        displayTextLine("File: " + filename);
    }
    else {
        displayTextLine("Export failed!");
    }

    delay(2000);
    return true;
}

void BLETesla::setup() {
    tft.setTextSize(1);
    tft.setTextColor(bruceConfig.priColor, bruceConfig.bgColor);

    NimBLEDevice::init("");
    pBLEScan = NimBLEDevice::getScan();
    pBLEScan->setAdvertisedDeviceCallbacks(new TeslaAdvertisedDeviceCallbacks());
    pBLEScan->setActiveScan(true);
    pBLEScan->setInterval(SCAN_INTERVAL);
    pBLEScan->setWindow(SCAN_WINDOW);
}

void BLETesla::loop() {
    drawMainBorder();
    displayTextLine("Tesla Radar Starting...");
    delay(1000);

    while (!check(EscPress)) {
        // Check for clear command using KeyStroke system
        if (KeyStroke.pressed) {
            for (auto keyChar : KeyStroke.word) {
                if (keyChar == 'c' || keyChar == 'C') {
                    teslaHistory.clear();
                    displayTextLine("History cleared!");
                    delay(500);
                    KeyStroke.Clear();
                    break;
                }
                else if (keyChar == 'e' || keyChar == 'E') {
                    exportTeslaHistory();
                    KeyStroke.Clear();
                    break;
                }
            }
            KeyStroke.Clear();
        }

        // BLE scan
        pBLEScan->start(1, false);

        // Update display
        updateTeslaDisplay();

        delay(100);
    }

    // Cleanup
    displayTextLine("Exiting...");
    delay(500);

    pBLEScan->stop();
    pBLEScan->clearResults();
    NimBLEDevice::deinit(true);
}
